


sudo: required
services:
  - docker

before_install:
  - docker build -t vlad/react-test -f ./client/Dockerfile.dev ./client
  

script:
  - docker run -e CI=true vlad/react-test npm test -- --coverage


after_success:
  - docker build -t vlad/multi-client ./client
  - docker build -t vlad/multi-nginx  ./nginx
  - docker build -t vlad/multi-server ./server
  - docker build -t vlad/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push vlad/multi-client
  - docker push vlad/multi-nginx
  - docker push vlad/multi-server
  - docker push vlad/multi-worker

