


sudo: required
services:
  - docker

before_install:
  - docker build -t banderlogic/react-test -f ./client/Dockerfile.dev ./client
  

script:
  - docker run -e CI=true banderlogic/react-test npm test -- --coverage


after_success:
  - docker build -t banderlogic/multi-client ./client
  - docker build -t banderlogic/multi-nginx  ./nginx
  - docker build -t banderlogic/multi-server ./server
  - docker build -t banderlogic/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push banderlogic/multi-client
  - docker push banderlogic/multi-nginx
  - docker push banderlogic/multi-server
  - docker push banderlogic/multi-worker

